import type { Formula } from '@sizing/engine';

// Total cost page (cost.ts). Prices are not settings: they come from the Total cost page or the cost defaults
// on the Configurations page, so these formulas name no setting keys.
export const WEB_FORMULAS: Formula[] = [
  {
    id: 'cost.subscription',
    area: 'Total cost',
    group: 'Elastic subscription',
    title: 'Subscription per year',
    formula: 'subscription = license units for all sites × price per license unit per year\nWith a discount: subscription = list price − list price × discount %\nBasic license: 0',
    explanation: 'License units (ERU) are the blocks of memory Elastic licenses by. The discount applies to the Elastic subscription only, never to hardware or running costs.',
    constantKeys: [],
    source: 'Total cost page, discount added by Dan (2026-09)',
    code: 'web cost.ts subscriptionCost',
  },
  {
    id: 'cost.hardware',
    area: 'Total cost',
    group: 'Hardware',
    title: 'Hardware per year',
    formula: 'servers = total node memory (GB) for all sites × server price per GB of memory\ndisks = sum over disk types of (disk TB for all sites × price per TB for that type)\nhardware per year = (servers + disks) ÷ hardware life in years',
    explanation: 'The purchase price is spread evenly over the years you keep the hardware. The server price per GB of memory covers the whole server (case, processors and memory).',
    constantKeys: [],
    source: 'Total cost page',
    code: 'web cost.ts hardwareCost',
  },
  {
    id: 'cost.object_storage',
    area: 'Total cost',
    group: 'Running costs',
    title: 'Object storage per year',
    formula: 'object storage per year = object storage TB for all sites × price per TB per month × 12',
    explanation: 'Object storage is cheap bulk storage, such as Amazon S3, that holds the cold and frozen data. Without cold or frozen data it costs nothing.',
    constantKeys: [],
    source: 'Total cost page, D26',
    code: 'web cost.ts objectCost',
  },
  {
    id: 'cost.hosting',
    area: 'Total cost',
    group: 'Running costs',
    title: 'Hosting, power and rack per year',
    formula: 'hosting per year = number of nodes for all sites × hosting price per node per month × 12',
    explanation: 'Covers rack space, power, cooling and network for each node.',
    constantKeys: [],
    source: 'Total cost page',
    code: 'web cost.ts hostingCost',
  },
  {
    id: 'cost.operations',
    area: 'Total cost',
    group: 'Running costs',
    title: 'Operations staff per year',
    formula: 'operations per year = operations staff (people) × cost per person per year',
    explanation: 'The cost per person is salary plus benefits and overheads. Fractions of a person are allowed.',
    constantKeys: [],
    source: 'Total cost page',
    code: 'web cost.ts opsCost',
  },
  {
    id: 'cost.year_total',
    area: 'Total cost',
    group: 'Totals',
    title: 'Cost for one year',
    formula: 'year total = subscription + hardware + object storage + hosting + operations\nA part without its prices is left out of the total and shown as missing.',
    explanation: 'Each part is worked out for the cluster sized for that year. Leaving a price blank removes that part instead of guessing it.',
    constantKeys: [],
    source: 'Total cost page',
    code: 'web cost.ts annualCosts, sumLines',
  },
  {
    id: 'cost.term',
    area: 'Total cost',
    group: 'Totals',
    title: 'Cost over the term',
    formula: 'Size a workload: year k uses the cluster sized for k years of growth\nTest hardware limits: every year uses the same cluster\nterm total = sum of the year totals, for the length of the estimate (3 years unless changed)',
    explanation: 'When the data grows, the cluster (and so the hardware and license) grows with it year by year. When the hardware is fixed, every year costs the same.',
    constantKeys: [],
    source: 'Total cost page, D24',
    code: 'web cost.ts resultsByYear, termCosts',
  },
];
