import type { Formula } from './types.ts';

// Multiple sites (D32) and Compare models (D33): how servers become nodes, whether they fit, and what each
// deployment model licenses. Code: topology.ts, plus the automatic master rule in the web app (D37).
export const FORMULAS: Formula[] = [
  // ---- Multiple sites: servers into nodes -------------------------------------------------------------
  {
    id: 'sites.nodes_per_server',
    area: 'Multiple sites',
    group: 'Servers into nodes',
    title: 'Nodes on each data server',
    formula: 'nodes per server = ROUNDDOWN(server memory ÷ largest practical node memory), at least 1\nA value typed in "Nodes / server" always wins.',
    explanation: 'A big server is split into several Elasticsearch nodes, each no larger than the practical node size. A node is one running copy of Elasticsearch.',
    constantKeys: ['node_ram_practical_max_gb'],
    source: 'D32',
    code: 'topology.ts nodesPerServer',
  },
  {
    id: 'sites.single_node_roles',
    area: 'Multiple sites',
    group: 'Servers into nodes',
    title: 'Roles that run one node per server',
    formula: 'nodes per server = 1 for frozen, machine learning, master, Kibana, Fleet and APM servers',
    explanation: 'These roles do not split a server into several nodes. Master, Kibana, Fleet and APM also keep at most one copy per server, so losing a server never loses two votes or both copies of a service.',
    constantKeys: [],
    source: 'D32',
    code: 'topology.ts SINGLE_NODE_ROLES, SPREAD_ROLES',
  },
  {
    id: 'sites.node_template',
    area: 'Multiple sites',
    group: 'Servers into nodes',
    title: 'Node size used for sizing a site',
    formula: 'node memory = server memory ÷ nodes per server\nnode disk = server disk ÷ nodes per server\nnode cores = server cores ÷ nodes per server',
    explanation: 'Each site is sized with nodes cut from the first server group listed for each tier, so the node count matches the hardware the site really has.',
    constantKeys: [],
    source: 'D32',
    code: 'topology.ts siteOptions',
  },

  // ---- Multiple sites: what each site holds ----------------------------------------------------------
  {
    id: 'sites.holdings',
    area: 'Multiple sites',
    group: 'What each site holds',
    title: 'Data each site must hold',
    formula: 'Independent: a site holds only the data it takes in.\nDisaster recovery: the main site holds its own data; each standby site holds its own data plus a copy of the main site\'s data.\nActive-active: every site holds its own data plus a copy of every other site\'s data.',
    explanation: 'The site relationship decides how much data each site stores. Copying data between sites is called cross-cluster replication.',
    constantKeys: [],
    source: 'D32',
    code: 'topology.ts holdings',
  },

  // ---- Multiple sites: does it fit -------------------------------------------------------------------
  {
    id: 'sites.data_servers_needed',
    area: 'Multiple sites',
    group: 'Does it fit',
    title: 'Servers needed for a data tier',
    formula: 'servers needed = ROUNDUP((nodes needed − spare nodes) ÷ nodes per server) + spare servers',
    explanation: 'The spare is a whole server, not a single node: when a server fails, every node on it goes down together. The tier fits when servers needed is no more than the servers listed.',
    constantKeys: ['failover_nodes_per_tier'],
    source: 'D32',
    code: 'topology.ts fitFor',
  },
  {
    id: 'sites.support_servers_needed',
    area: 'Multiple sites',
    group: 'Does it fit',
    title: 'Servers needed for master, Kibana, Fleet, APM, machine learning and coordinating',
    formula: 'Self-managed: servers needed = ROUNDUP(nodes needed ÷ nodes per server)\nECK and ECE: nodes per server = ROUNDDOWN(usable server memory ÷ node memory), at most 1 for master, Kibana, Fleet and APM',
    explanation: 'Supporting nodes are placed on the servers listed for their role. If no servers are listed for a role, it is shown as not placed (run elsewhere) rather than as a shortfall.',
    constantKeys: ['node_ram_practical_max_gb'],
    source: 'D32, D33',
    code: 'topology.ts fitFor',
  },
  {
    id: 'sites.headroom',
    area: 'Multiple sites',
    group: 'Does it fit',
    title: 'Spare room',
    formula: 'spare room = the largest multiple of today\'s data volume that still fits every site\nFound by trying larger and smaller multiples until they meet (halving the gap 50 times).',
    explanation: 'A spare room of 1.5× means the servers could take 50% more data before something runs out. The result also names the site and role that runs out first.',
    constantKeys: [],
    source: 'D32',
    code: 'topology.ts sizeTopology',
  },
  {
    id: 'sites.totals',
    area: 'Multiple sites',
    group: 'Totals',
    title: 'Totals across sites',
    formula: 'total memory = sum of each site\'s memory\ntotal license units = sum of each site\'s license units\nservers needed = sum over sites of servers needed for every placed role',
    explanation: 'Each site is its own cluster and is licensed separately, so license units add up site by site.',
    constantKeys: [],
    source: 'D32',
    code: 'topology.ts sizeTopology',
  },
  {
    id: 'sites.auto_masters',
    area: 'Multiple sites',
    group: 'Automatic master nodes',
    title: 'Adding and removing master nodes automatically',
    formula: 'data nodes = sum over data servers of (servers × nodes per server)\nWhen an edit takes data nodes from below the threshold to at or above it, and no master row is left: add the master row the sizing table gives for that many data nodes.\nWhen an edit takes data nodes back below the threshold: remove the master rows (not when master servers are the ECE control plane).',
    explanation: 'Master nodes are small nodes that keep the cluster organized. Large clusters need their own; small ones let the data nodes do it. Only crossing the threshold changes anything, so masters you add or delete by hand stay as you left them.',
    constantKeys: ['masters.sizing', 'node_ram_practical_max_gb', 'vcpu_per_ram_gb'],
    source: 'D37',
    code: 'web state.ts withAutoMasters',
  },

  // ---- Compare models: servers into nodes per model -------------------------------------------------
  {
    id: 'models.self_managed_layout',
    area: 'Compare models',
    group: 'Servers into nodes',
    title: 'Self-managed: nodes on a server',
    formula: 'nodes per server = ROUNDDOWN(server memory ÷ largest practical node memory), at least 1\nnode memory = server memory ÷ nodes per server',
    explanation: 'Self-managed means Elasticsearch installed directly on the servers, so all of each server\'s memory is available to nodes.',
    constantKeys: ['node_ram_practical_max_gb'],
    source: 'D33',
    code: 'topology.ts serverLayout',
  },
  {
    id: 'models.eck_layout',
    area: 'Compare models',
    group: 'Servers into nodes',
    title: 'ECK: containers on a server',
    formula: 'usable memory = server memory − Kubernetes memory reserve\ncontainers per server = ROUNDUP(usable memory ÷ largest practical node memory), at least 1\ncontainer memory = usable memory ÷ containers per server\ncontainer cores = (server cores − Kubernetes core reserve) ÷ containers per server',
    explanation: 'ECK runs Elasticsearch in containers managed by Kubernetes. Each server keeps some memory and a core for Kubernetes itself; the rest is shared by the Elasticsearch containers.',
    constantKeys: ['eck.k8s_reserve_ram_gb', 'eck.k8s_reserve_vcpu', 'node_ram_practical_max_gb'],
    source: 'D33',
    code: 'topology.ts serverLayout',
  },
  {
    id: 'models.ece_layout',
    area: 'Compare models',
    group: 'Servers into nodes',
    title: 'ECE: instances on a server',
    formula: 'usable memory = server memory × planned share\ninstances per server = ROUNDDOWN(usable memory ÷ largest practical node memory), at least 1\ninstance memory = the smaller of largest practical node memory and usable memory ÷ instances per server',
    explanation: 'ECE is Elastic\'s private-cloud platform installed on the servers. Servers that host Elasticsearch (allocators) are only planned to a share of their memory, leaving room for the platform.',
    constantKeys: ['ece.allocator_planning_fraction', 'node_ram_practical_max_gb'],
    source: 'D33',
    code: 'topology.ts serverLayout',
  },
  {
    id: 'models.ece_control_plane',
    area: 'Compare models',
    group: 'Does it fit',
    title: 'ECE: control-plane hosts',
    formula: 'master servers needed = the larger of the control-plane host count and the servers needed for Elasticsearch masters\nEach master server must have at least the control-plane memory.\nmasters per host = at most 1 if (server memory − control-plane memory) × planned share holds one master',
    explanation: 'With ECE, the master servers become the control plane, the servers that run ECE itself. Elasticsearch master nodes use what those servers have left, one per server.',
    constantKeys: ['ece.control_plane_hosts', 'ece.control_plane_ram_gb', 'ece.allocator_planning_fraction'],
    source: 'D33',
    code: 'topology.ts fitFor',
  },

  // ---- Compare models: license -------------------------------------------------------------------------
  {
    id: 'models.eru_self_managed',
    area: 'Compare models',
    group: 'License',
    title: 'Self-managed license units',
    formula: 'license units = ROUNDUP(memory of Elasticsearch, Kibana and APM nodes ÷ memory per license unit)',
    explanation: 'An ERU (Enterprise Resource Unit) is the unit Elastic licenses by, a block of memory. Self-managed counts the memory of the nodes that are licensed.',
    constantKeys: ['eru_gb', 'eru.counted_components'],
    source: 'D3, D33',
    code: 'license.ts (via forward)',
  },
  {
    id: 'models.eru_eck',
    area: 'Compare models',
    group: 'License',
    title: 'ECK license units',
    formula: 'container memory (GiB) = container memory (GB) × 1,000,000,000 ÷ 1,073,741,824\nlicense units = ROUNDUP(container memory in GiB ÷ memory per license unit)',
    explanation: 'ECK licenses the memory limit set on each Elasticsearch, Kibana and APM container, measured in GiB (a slightly larger unit than GB). Elastic Agent containers are free.',
    constantKeys: ['eru_gb', 'eru.counted_components'],
    source: 'D33, P6',
    code: 'topology.ts licenseFor, gbToGib',
  },
  {
    id: 'models.eru_ece',
    area: 'Compare models',
    group: 'License',
    title: 'ECE license units',
    formula: 'license units = ROUNDUP(sum over used roles of (servers needed × server memory) ÷ memory per license unit)',
    explanation: 'ECE licenses all the memory of every server it uses, busy or not, including the control-plane hosts.',
    constantKeys: ['eru_gb'],
    source: 'D33',
    code: 'topology.ts licenseFor',
  },
  {
    id: 'models.best',
    area: 'Compare models',
    group: 'Comparison',
    title: 'Best on each measure',
    formula: 'Among the models that fit (or all of them, when none fit):\nfewest license units, most spare room, fewest servers each get a star',
    explanation: 'There is no single winner. Each measure is marked separately so the trade-off between cost, spare capacity and server count stays visible.',
    constantKeys: [],
    source: 'D33',
    code: 'topology.ts compareModels',
  },
];
